apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexpong
resources:
  - ../../base
patches:
  - path: backend-service-nodeport.yaml
  - path: frontend-service-nodeport.yaml
