apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexpong
resources:
  - namespace.yaml
  - replay-pvc.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - worker-deployment.yaml
