apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: codexpong
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: codexpong
spec:
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: codexpong
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
